// TOTALCOUNT ACTION CREATE  

// TOTALCOUNT GET ACTION 
export const GET_TOTALCOUNT_PROGRESS = "GET_TOTALCOUNT_PROGRESS"
export const GET_TOTALCOUNT_ERROR = "GET_TOTALCOUNT_ERROR"
export const GET_TOTALCOUNT_SUCCESS = "GET_TOTALCOUNT_SUCCESS"
