// ELECTION ACTION CREATE  

// ELECTION GET ACTION 
export const GET_ELECTION_PROGRESS = "GET_ELECTION_PROGRESS"
export const GET_ELECTION_ERROR = "GET_ELECTION_ERROR"
export const GET_ELECTION_SUCCESS = "GET_ELECTION_SUCCESS"

// ELECTION GET ACTION 
export const POST_ELECTION_PROGRESS = "POST_ELECTION_PROGRESS"
export const POST_ELECTION_ERROR = "POST_ELECTION_ERROR"
export const POST_ELECTION_SUCCESS = "POST_ELECTION_SUCCESS"