// PARTYCONNECT ACTION CREATE  

// PARTYCONNECT GET ACTION 
export const GET_PARTYCONNECT_PROGRESS = "GET_PARTYCONNECT_PROGRESS"
export const GET_PARTYCONNECT_ERROR = "GET_PARTYCONNECT_ERROR"
export const GET_PARTYCONNECT_SUCCESS = "GET_PARTYCONNECT_SUCCESS"

// PARTYCONNECT GET ACTION 
export const POST_PARTYCONNECT_PROGRESS = "POST_PARTYCONNECT_PROGRESS"
export const POST_PARTYCONNECT_ERROR = "POST_PARTYCONNECT_ERROR"
export const POST_PARTYCONNECT_SUCCESS = "POST_PARTYCONNECT_SUCCESS"  