// PARTY ACTION CREATE  

// PARTY GET ACTION 
export const GET_PARTY_PROGRESS = "GET_PARTY_PROGRESS"
export const GET_PARTY_ERROR = "GET_PARTY_ERROR"
export const GET_PARTY_SUCCESS = "GET_PARTY_SUCCESS"

// PARTY GET ACTION 
export const POST_PARTY_PROGRESS = "POST_PARTY_PROGRESS"
export const POST_PARTY_ERROR = "POST_PARTY_ERROR"
export const POST_PARTY_SUCCESS = "POST_PARTY_SUCCESS"  